spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 18821203182
    url: jdbc:mysql://127.0.0.1:3306/imooc?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

